#!/usr/bin/env python3
"""
stage4_build_cell_wrapper.py

Emits tb/uvm/dut_cells.sv:
  - 23 DUT chains (golden + 22 mutants), each with uniquely renamed modules
  - A wrapper module `dut_cells` that muxes outputs based on +CELL=<name>

Reads:
  rtl/qpsk_modulator.sv, rtl/channel.sv, rtl/qpsk_demodulator.sv
  mutants/<cell>/manifest.json  (22 mutant directories)

Writes:
  tb/uvm/dut_cells.sv
"""
import json
import re
from pathlib import Path

ROOT    = Path(__file__).resolve().parent
RTL     = ROOT / "rtl"
MUTANTS = ROOT / "mutants"
OUT     = ROOT / "tb" / "uvm" / "dut_cells.sv"

GOLDEN = {
    "qpsk_modulator.sv":   "qpsk_modulator",
    "channel.sv":          "channel",
    "qpsk_demodulator.sv": "qpsk_demodulator",
}


def sanitize(name: str) -> str:
    # 'W-01_mod_latency_plus1' -> 'W01_mod_latency_plus1'
    return re.sub(r'[^A-Za-z0-9_]', '_', name)


def rename_module(text: str, old: str, new: str) -> str:
    # Rename only the module declaration line
    return re.sub(rf'\bmodule\s+{re.escape(old)}\b', f'module {new}', text)


def load_golden() -> dict:
    return {fname: (RTL / fname).read_text() for fname in GOLDEN}


def load_cells() -> list:
    """Return list of (cell_name, {file_basename: source_text})."""
    g = load_golden()
    cells = [("golden", dict(g))]
    for d in sorted(MUTANTS.iterdir()):
        if not d.is_dir():
            continue
        mf = d / "manifest.json"
        if not mf.exists():
            continue
        try:
            m = json.loads(mf.read_text())
        except Exception as e:
            print(f"[skip] {d.name}: bad manifest ({e})")
            continue
        target = Path(m.get("target_file", "")).name
        if target not in GOLDEN:
            print(f"[skip] {d.name}: unknown target '{target}'")
            continue
        mutated = (d / target).read_text()
        files = dict(g)          # start from all-golden
        files[target] = mutated  # override the mutated one
        cells.append((d.name, files))
    return cells


def emit(cells: list) -> str:
    L = []
    L.append("// AUTO-GENERATED by stage4_build_cell_wrapper.py — do not edit.")
    L.append(f"// {len(cells)} DUT chains; runtime select via +CELL=<name>.")
    L.append("`timescale 1ns/1ps")
    L.append("")

    # ---- renamed modules ----
    for cell_name, files in cells:
        suffix = sanitize(cell_name)
        for fname, src in files.items():
            old_mod = GOLDEN[fname]
            new_mod = f"{old_mod}_{suffix}"
            L.append(f"// ====================================================")
            L.append(f"// cell={cell_name}  file={fname}")
            L.append(f"// ====================================================")
            L.append(rename_module(src, old_mod, new_mod))
            L.append("")

    # ---- wrapper ----
    L.append("module dut_cells (")
    L.append("    input  logic        clk,")
    L.append("    input  logic        rst,")
    L.append("    input  logic [31:0] ch_seed,")
    L.append("    input  logic        valid_in,")
    L.append("    input  logic [1:0]  bits_in,")
    L.append("    output logic        valid_out,")
    L.append("    output logic [1:0]  bits_out")
    L.append(");")
    L.append("    string cell_name;")
    L.append("    initial if (!$value$plusargs(\"CELL=%s\", cell_name)) cell_name = \"golden\";")
    L.append("")

    # ---- nets + instances per cell ----
    for cell_name, _ in cells:
        s = sanitize(cell_name)
        vm, vc, v = f"{s}_vmod", f"{s}_vch", f"{s}_vout"
        im, qm, ic, qc = (f"{s}_imod", f"{s}_qmod",
                          f"{s}_ich", f"{s}_qch")
        b = f"{s}_bout"
        L.append(f"    // --- {cell_name} ---")
        L.append(f"    logic              {vm}, {vc}, {v};")
        L.append(f"    logic signed [7:0] {im}, {qm}, {ic}, {qc};")
        L.append(f"    logic [1:0]        {b};")
        L.append(f"    qpsk_modulator_{s} u_{s}_mod (")
        L.append(f"        .clk(clk), .rst(rst), .valid_in(valid_in), .bits(bits_in),")
        L.append(f"        .valid_out({vm}), .i_out({im}), .q_out({qm}));")
        L.append(f"    channel_{s} u_{s}_ch (")
        L.append(f"        .clk(clk), .rst(rst), .seed(ch_seed),")
        L.append(f"        .valid_in({vm}), .i_in({im}), .q_in({qm}),")
        L.append(f"        .valid_out({vc}), .i_out({ic}), .q_out({qc}));")
        L.append(f"    qpsk_demodulator_{s} u_{s}_demod (")
        L.append(f"        .clk(clk), .rst(rst), .valid_in({vc}),")
        L.append(f"        .i_in({ic}), .q_in({qc}),")
        L.append(f"        .valid_out({v}), .bits({b}));")
        L.append("")

    # ---- mux ----
    L.append("    always_comb begin")
    L.append("        valid_out = 1'b0;")
    L.append("        bits_out  = 2'b00;")
    L.append("        case (cell_name)")
    for cell_name, _ in cells:
        s = sanitize(cell_name)
        L.append(f'            "{cell_name}": begin '
                 f'valid_out = {s}_vout; bits_out = {s}_bout; end')
    L.append("            default: ;")
    L.append("        endcase")
    L.append("    end")
    L.append("endmodule")
    return "\n".join(L) + "\n"


def main():
    cells = load_cells()
    print(f"Cells: {len(cells)}")
    for c, _ in cells:
        print(f"  - {c}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(emit(cells))
    print(f"\nWrote {OUT}")


if __name__ == "__main__":
    main()